[Service]
RestrictNamespaces=yes
ProtectControlGroups=yes
PrivateDevices=yes
SystemCallArchitectures=native
RestrictSUIDSGID=yes
RemoveIPC=yes
UMask=0027
RestrictRealtime=yes
ProtectClock=yes
ProtectHostname=yes
ProtectKernelLogs=yes
ProtectKernelTunables=yes
LockPersonality=yes
